CC=g++
CFLAGS=-I.
	
	
compile:
	${CC} -c class_def.cpp
	${CC} -c main.cpp
	${CC} -c SerwerTCP.cpp
	${CC} -c SerwerMULTICAST.c
	${CC} main.o class_def.o SerwerTCP.o SerwerMULTICAST.o -o RYZYKO
	rm *.o
	
