CC=gcc

#TODO improve this makefile
all: clientMulti clientTCP

clientMulti: clientMulti.c 
	gcc -o clientMulti clientMulti.c
	
clientTCP: clientTCP.c 
	gcc -o clientTCP clientTCP.c 	

clean:
	rm clientMulti clientTCP
